export type CalendarItemKind = 'event' | 'task';
export type CalendarItemStatus =
  | 'scheduled'
  | 'in-progress'
  | 'completed'
  | 'cancelled';
export type CalendarItemPriority = 'low' | 'medium' | 'high';

export interface MeetingDetail {
  enabled: boolean;
  provider: 'google_meet' | 'jitsi' | 'custom';
  joinUrl?: string;
  meetingId?: string;
  passcode?: string;
  autoGenerated?: boolean;
}

export interface AiAgendaDetail {
  summary?: string;
  topics?: string[];
  objectives?: string[];
  preparationNotes?: string[];
  formattedMarkdown?: string;
  generatedAt?: string | Date;
}

/**
 * Calendar-library neutral shape for the first calendar migration.
 * API records should be adapted to this type instead of leaking a library's
 * event contract throughout the application.
 */
export interface CalendarItem {
  id: string;
  title: string;
  start: Date;
  end: Date;
  allDay?: boolean;
  kind: CalendarItemKind;
  status: CalendarItemStatus;
  priority?: CalendarItemPriority;
  assigneeNames?: string[];
  draggable?: boolean;
  resizable?: boolean;
  meeting?: MeetingDetail;
  aiAgenda?: AiAgendaDetail;
}

export function updateCalendarItemTiming(
  item: CalendarItem,
  timing: Pick<CalendarItem, 'start' | 'end' | 'allDay'>
): CalendarItem {
  return { ...item, ...timing };
}

export function getProjectFormTitle(form: any): string {
  if (!form) return 'Untitled';
  const name =
    form.identity?.name ||
    form.name ||
    form.title ||
    form.metadata?.name ||
    form.identity?.title ||
    form.metadata?.title ||
    form.formReference;
  return typeof name === 'string' && name.trim().length > 0
    ? name.trim()
    : 'Untitled';
}

