export const routes = {
  executive: {
    dashboard: '/executive',
  },
  storage: {
    index: '/storage',
    files: '/storage/files',
    manager: '/storage/manager',
  },
  file: {
    dashboard: '/storage/files',
    manager: '/storage/manager',
  },

  eventCalendar: '/event-calendar',
  calendarManagement: '/calendar-management',
  networkCreate: '/network/create',
  networkManage: '/network/manage',
  projectBoard: '/projects/dashboard',
  intelligence: '/intelligence',
  library: '/sabyform/templates',
  studioModuleReports: '/studio/module-reports',
  studioModuleTracking: '/studio/module-tracking',
  formview: (projectId: string) => `/form/${projectId}`,
  forms: {
    index: '/forms',
    details: (projectId: string) => `/forms/${projectId}`,
    preview: (projectId: string) => `/forms/${projectId}/preview`,
  },
  apis: '/apis',
  apiCenter: '/apis/api-center',
  apiUserSettings: '/apis/user-settings',
  apiGoLive: '/apis/go-live',
  apiApprovals: '/apis/approvals',
  studioV2: {
    index: '/studio',
    onboarding: '/studio/onboarding',
    modules: '/studio/modules',
    templates: '/studio/modules/templates',
    team: '/studio/team',
    users: '/studio/users',
    network: '/studio/network',
    vault: '/studio/vault',
    automations: '/studio/automations',
    billing: '/studio/billings',
    security: '/studio/security',
    workspaceNew: '/studio/workspace/new',
    workspace: (workspaceId: string) => `/studio/workspace/${workspaceId}`,
  },
  inmails: '/inmails',
  cms: '/cms',
  logs: '/log-dashboard',
  submissions: '/submissions',
  submissionDetails: (id: string) => `/submissions/${id}`,
  moduleReport: (moduleId: string) => `/module-report/${moduleId}`,
  permDashboard: '/perm-dashboard',
  permProject: (projectId: string) => `/perm-dashboard/${projectId}`,
  baseline: {
    dashboard: '/reports/baseline-intelligence',
    network: '/reports/baseline-intelligence/network',
    compliance: '/reports/baseline-intelligence/compliance',
    leaderboard: '/reports/baseline-intelligence/leaderboard',
    // New sub-pages for better organization
    usersDemographics: '/reports/baseline-intelligence/users-demographics',
    networksGeographics: '/reports/baseline-intelligence/networks-geographics',
    propertyDistributions:
      '/reports/baseline-intelligence/property-distributions',
    insightsRecommendations:
      '/reports/baseline-intelligence/insights-recommendations',
  },
  users: {
    permissionsTable: '/users/permissions',
    rolesTable: '/users/roles',
    editRole: (roleId: string) => `/users/roles/${roleId}/edit`,
    usersTable: '/users/list',
    profile: (userId: string) => `/users/profile/${userId}`,
    levelsTable: '/users/level',
    structuresTable: '/users/structure',
  },

  network: {
    level: '/network/level',
    structure: '/network/structure',
  },

  node: {
    index: '/node',
    create: '/node/create',
    manage: '/node/manage',
    distribution: '/node/distribution',
  },
  imageViewer: '/image-viewer',
  chat: '/',
  sabyMeet: '/saby/meet',
  pricing: '/pricing',
  billing: '/billing',
  documentation: '/documentation',
  blog: '/blog',
  partners: '/partners',
  help: '/help',
  helpSupport: '/help-support',
  productUpdates: '/product-updates',

  emailTemplates: '/email-templates',
  profile: '/profile',
  welcome: '/studio/onboarding',
  comingSoon: '/coming-soon',
  accessDenied: '/access-denied',
  notFound: '/not-found',
  maintenance: '/maintenance',
  blank: '/blank',

  auth: {
    signUp1: '/auth/sign-up-1',
    signUp2: '/auth/sign-up',
    // sign in
    signIn1: '/auth/sign-in-1',
    signIn2: '/auth/sign-in',
    // forgot password
    forgotPassword1: '/auth/forgot-password-1',
    forgotPassword: '/auth/forgot-password',
    // OTP
    otp1: '/auth/otp-1',
    otp2: '/auth/otp',
    resetPassword: '/auth/reset-password',
  },

  auditTrail: '/audit-trail',
  payments: '/payments',
  signIn: '/auth/sign-in',
  faqs: '/faqs',
};
